In [3]:
import sys
import os

# Add the project root to Python's search path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Now import the dataframes
from scripts.data_loading import consumers, accounts, transactions, category_mapping

In [ ]:
# individual consumer data
consumers.head()

  prism_consumer_id evaluation_date  credit_score  DQ_TARGET
0                 0      2021-09-01         726.0        0.0
1                 1      2021-07-01         626.0        0.0
2                 2      2021-05-01         680.0        0.0
3                 3      2021-03-01         734.0        0.0
4                 4      2021-10-01         676.0        0.0

In [ ]:
# account information
accounts.head()

  prism_consumer_id prism_account_id account_type balance_date   balance
0              3023                0      SAVINGS   2021-08-31     90.57
1              3023                1     CHECKING   2021-08-31    225.95
2              4416                2      SAVINGS   2022-03-31  15157.17
3              4416                3     CHECKING   2022-03-31     66.42
4              4227                4     CHECKING   2021-07-31   7042.90

In [ ]:
# transactional data
transactions.head()

,prism_consumer_id,prism_transaction_id,category,amount,credit_or_debit,posted_date
0,3023,0,4,0.05,CREDIT,2021-04-16
1,3023,1,12,481.56,CREDIT,2021-04-30
2,3023,2,4,0.05,CREDIT,2021-05-16
3,3023,3,4,0.07,CREDIT,2021-06-16
4,3023,4,4,0.06,CREDIT,2021-07-16

In [ ]:
# category mapping
category_mapping

    category_id               category
0             0          SELF_TRANSFER
1             1      EXTERNAL_TRANSFER
2             2                DEPOSIT
3             3               PAYCHECK
4             4          MISCELLANEOUS
5             5   PAYCHECK_PLACEHOLDER
6             6                 REFUND
7             7      INVESTMENT_INCOME
8             8         OTHER_BENEFITS
9             9  UNEMPLOYMENT_BENEFITS
10           10   SMALL_DOLLAR_ADVANCE
11           11                    TAX
12           12                   LOAN
13           13              INSURANCE
14           14     FOOD_AND_BEVERAGES
15           15          UNCATEGORIZED
16           16    GENERAL_MERCHANDISE
17           17             AUTOMOTIVE
18           18              GROCERIES
19           19               ATM_CASH
20           20          ENTERTAINMENT
21           21                 TRAVEL
22           22     ESSENTIAL_SERVICES
23           23           ACCOUNT_FEES
24           24       HOME_IMPROVEMENT
25           25              OVERDRAFT
26           26    CREDIT_CARD_PAYMENT
27           27     HEALTHCARE_MEDICAL
28           28                   PETS
29           29              EDUCATION
30           30        GIFTS_DONATIONS
31           31        BILLS_UTILITIES
32           32               MORTGAGE
33           33       CHILD_DEPENDENTS
34           34                   RENT
35           35                   BNPL
36           36              AUTO_LOAN
37           37      BANKING_CATCH_ALL
38           38                   DEBT
39           39                FITNESS
40           40          TRANSPORATION
41           41                  LEGAL
42           42    GOVERNMENT_SERVICES
43           43         RISK_CATCH_ALL
44           44                RTO_LTO
45           45             INVESTMENT
46           46               GAMBLING
47           47     CORPORATE_PAYMENTS
48           48          TIME_OR_STUFF
49           49                PENSION

In [ ]:
accounts['balance_date'] = pd.to_datetime(accounts['balance_date'])
transactions['posted_date'] = pd.to_datetime(transactions['posted_date'])

NameError: name 'pd' is not defined